name: 'Update image URI then deploy - Dokploy'
description: 'Deploy an application with image URI to Dokploy'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  dokploy_url:
    description: 'Dokploy base URL, e.g. https://dokploy.example.com'
    required: true
  api_token:
    description: 'Dokploy API token'
    required: true
  compose_id:
    description: 'Dokploy compose ID'
    required: false
  application_id:
    description: 'Dokploy application ID'
    required: false
  image_uri:
    description: 'Image URI'
    required: false
runs:
  using: "composite"
  steps:
    - name: Update app docker provider
      if: ${{ inputs.application_id }} 
      shell: bash
      env:
        DOKPLOY_URL: ${{ inputs.dokploy_url }}
        DOKPLOY_API_TOKEN: ${{ inputs.api_token }}
        DOKPLOY_APPLICATION_ID: ${{ inputs.application_id }}
        DOKPLOY_IMAGE_URI: ${{ inputs.image_uri }}
      run: |
        response=$(curl -X 'POST' \
          "$DOKPLOY_URL/api/application.saveDockerProvider" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "x-api-key: $DOKPLOY_API_TOKEN" \
          -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\", \"dockerImage\": \"$DOKPLOY_IMAGE_URI\"}" \
          -w "%{http_code}" \
          -o /dev/null \
          -s)

        if [ "$response" -ne 200 ]; then
          echo "Updating app docker provider failed with status code: $response"
          exit 1
        fi

    - name: Trigger deployment
      if: ${{ inputs.application_id }} 
      shell: bash
      env:
        DOKPLOY_URL: ${{ inputs.dokploy_url }}
        DOKPLOY_API_TOKEN: ${{ inputs.api_token }}
        DOKPLOY_APPLICATION_ID: ${{ inputs.application_id }}
      run: |
        response=$(curl -X 'POST' \
          "$DOKPLOY_URL/api/application.deploy" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "x-api-key: $DOKPLOY_API_TOKEN" \
          -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
          -w "%{http_code}" \
          -o /dev/null \
          -s)
        
        if [ "$response" -ne 200 ]; then
          echo "Deployment failed with status code: $response"
          exit 1
        fi

    - name: Trigger deployment
      if: ${{ inputs.compose_id }} 
      shell: bash
      env:
        DOKPLOY_URL: ${{ inputs.dokploy_url }}
        DOKPLOY_API_TOKEN: ${{ inputs.api_token }}
        DOKPLOY_COMPOSE_ID: ${{ inputs.compose_id }}
      run: |
        response=$(curl -s -X 'GET' \
          "$DOKPLOY_URL/api/compose.one?composeId=$DOKPLOY_COMPOSE_ID" \
          -H 'Accept: application/json' \
          -H "x-api-key: $DOKPLOY_API_TOKEN" \
        )
        
        app_name=$(echo $response | jq -r '.appName')
        stack_command="stack deploy -c docker-compose.yml --with-registry-auth $app_name --prune"
        
        response=$(curl -X 'POST' \
          "$DOKPLOY_URL/api/compose.update" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "x-api-key: $DOKPLOY_API_TOKEN" \
          -d "{\"composeId\": \"$DOKPLOY_COMPOSE_ID\", \"command\": \"$stack_command\"}" \
          -w "%{http_code}" \
          -o /dev/null \
          -s)

        if [ "$response" -ne 200 ]; then
          echo "Deployment failed with status code: $response"
          exit 1
        fi

        response=$(curl -X 'POST' \
          "$DOKPLOY_URL/api/compose.deploy" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "x-api-key: $DOKPLOY_API_TOKEN" \
          -d "{\"composeId\": \"$DOKPLOY_COMPOSE_ID\"}" \
          -w "%{http_code}" \
          -o /dev/null \
          -s)

        if [ "$response" -ne 200 ]; then
          echo "Deployment failed with status code: $response"
          exit 1
        fi